### ISSUE TITLE
64kbyte file chunks?

### ISSUE THREAD

**Issue by 1credit** [storj-archived/kfs#2]
That is only 8 modern disk sectors... that seems really small relative to the 2MB shards we use today.

**Comment by 161chihuahuas** [comment]
It's still the 2mb shards, but the individual key/value pairs embedded inside are 64k. This is how it already works today.

**Comment by 161chihuahuas** [comment]
The 2mb shards you are referring to are "levels" in LevelDB.

**Comment by 1credit** [comment]
Just seems like excessive overhead.  One pair per 2mb chucks, typically, feels a lot more effective.  At 64KB, thats 16K key/value pairs per GB.  For one file.  No wonder LevelDB is going nuts - 4, 194,304 key/value pairs per 256GB?

Is this adjustable?

**Comment by 161chihuahuas** [comment]
The number pairs is irrelevant. A 2mb chunk will contain data that corresponds to the same file, it's just split for efficient sequentially streaming reads. Since a single `get` will buffer the whole value into memory syncronously, it's better to perform a batch of smaller reads from the same file. LevelDB sorts these items lexicographically so it's still only one open file descriptor per 2mb.

**Comment by 161chihuahuas** [comment]
Also yes the `C` constant is adjustable and we will play with the most effective value.

**Comment by 1credit** [comment]
Just suspect that most filesystems, at least on TB class drives, are using a bigger filesystem blocksize.

Well, that was a bad suspecsion.  I checked a couple of large ext4 filesystems and all use 4KB blocks, so I guess your good.  Surprised by that size.

**Comment by 1credit** [comment]
Still trying to wrap my head around this... why would we not benefit from having one key/pair per shard?  Seems like that would significantly reduce overhead.  You indicated the size was adjustable.  Am I missing something?

**Comment by 161chihuahuas** [comment]
Yes:
1. Storing one full file shard in a pair means that the entire shard must be buffered into memory when read. Read multiple shards at once and you will have higher memory consumption.
2. When a renter wishes to retrieve a file, the farmer has to buffer the entire shard before transferring it. 
3. When a renter wishes to upload a file, the farmer has to buffer the entire shard before storing it.
4. Table files are 2MB, bigger shards mean more open files per read/write. 
5. Writes are first written to the log. Log is capped at 4MB. Writing shards bigger than the LOG can yield data loss in the event of a shutdown. 
6. When transferring the file shard as a stream, it is automatically chunked into 64k slices anyway. It's better to perform sequential reads on the full shard in sizes consistent with what is transferred so we don't unnecessarily buffer more than we can send during during a single tick of the event loop. 
7. If a renter disconnects during transfer and retries the transfer, reads will come out of the cache. If the shard is one value and it is bigger than the cache then we can't take advantage of using it the second time around and we must perform another full read.

**Comment by 1credit** [comment]
1,2,3 - Pretty trivial.  Say I have (8) nodes running with a concurrency of (8) and 2mb shards - total memory required would be 128mb.  Hardly noticeable on any modern system - might be a slight issues on older 256MB Pis, but totally, and predictably, controllable by then renter.  Not that a Pi use would be likely be running 8 nodes.  For a low-end PC with 4GB, this is ignoble.

4,5 - I'm pretty comfortable with 2mb shards.  I wouldn't want to go larger, but would consider smaller as acceptable.

6,7- Match buffer size to shard size makes sense, even if its chunked up for transmission, since all the data will be read and transmitted in every shard anyhow.  One downside is for the tail, but that can't be avoided.

7 - Note that the underlying OS is likely to keep the most recent data in cache anyhow, so its likely just a fast memory-to-memory transfer, no actual disk activity would occur.

Downside is the "double buffering" between the OS and Application level, but I believe that is an acceptable trade-off vs. the CPU & memory (table space) needed to manage 64kb key/pairs.  Most OS's will also control memory buffer usage in favor of application usage to avoid paging anyhow.

**Comment by 161chihuahuas** [comment]
The term "shard" is getting lost in translation here. A "shard" is a piece of file that is stored. It has a variable size that can any byte multiple starting at 8mib on up to 256mib and beyond. 

The 2mib files are the leveldb database files. So 1, 2, and 3 are _not_ trivial. Buffering an entire shard before transmitting it could consume all of the memory on a device like a raspberry pi. 

For 4 and 5, the size of the leveldb files cannot be changed. They will always be 2mib.

For 6 and 7, also I think you are confusing the term "shard" in this context. If I have a 256mib shard to serve, it would not make sense to buffer the whole thing before transmitting it. Especially if I'm serving many shards to renters at once.
