### ISSUE TITLE
S-Buckets don't fill evenly

### ISSUE THREAD

**Issue by Puychack** [storj-archived/kfs#27]
From the read.me file:

> Due to the nature of Kademlia's metric for determining distance, buckets will fill approximately evenly. The result of the XOR operation on the pseudo-random first bytes of the reference ID and hash should give any given bucket a relatively even chance of receiving any given file. 

The attached file is the du result of one node. All of my 12 nodes are showing the same non uniform filling.
[kfs_du.txt](https://github.com/Storj/kfs/files/529575/kfs_du.txt)
Please note that the filling is not always distributed around 080.s entry.

I wonder if this is related to the bad shard distribution in the storj network ?

**Comment by 161chihuahuas** [comment]
This is just poor language in the README. **Distribution** will be uniform, but that doesn't mean they will _fill_ evenly. Some shards are larger than others and will take more space. Also from the README:

> Even with a uniform distribution, as the node reaches capacity some buckets will fill sooner than others. Offers that would be sorted into these buckets should be declined and relayed to other nodes.

**Comment by Puychack** [comment]
Of course, but if distribution is uniform, I don't expect filling buckets to be grouped together.
The file show the distribution for 4 nodes in % of total sharddata.kfs size 
![kfs_distribution](https://cloud.githubusercontent.com/assets/20202167/19393436/0121a394-9235-11e6-8db4-38d5c5dba373.png)
And  for a given node, the filled buckets are filling up faster so don't think it's related to shard size.
Not a big deal by the way. Just to be sure it's not a problem. Because database won't make it to 8TB. Node will relay offers as soon as the main buckets are full ?
