### ISSUE TITLE
The media in the drive may have changed

### ISSUE THREAD

**Issue by MeijeSibbel** [storj-archived/kfs#50]
OS: windows 10
Storjshare-GUI: 4.1.0

```
events.js:160 Uncaught Error: IO error: D:\storj\storjshare-eadf0e\storjshare-6fba36\sharddata.kfs\108.s/000051.ldb: The media in the drive may have changed
```

![kfs](https://cloud.githubusercontent.com/assets/11735738/23827251/0b2c326e-06a7-11e7-815e-48f6bbded330.png)

**Comment by 161chihuahuas** [comment]
Sounds like a disk became unavailable, but either way open this in storjshare-gui if it persists
