### ISSUE TITLE
Error when stopping and restarting Daemon w/ google-drive-ocamlfuse

### ISSUE THREAD

**Issue by ne0ark** [storj-archived/kfs#51]
storjshare --version

  * daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0

`node Storj_Farmer_Contracts.js 

events.js:160
throw er; // Unhandled 'error' event
^
OpenError: IO error: lock /root/Storj/contracts.db/LOCK: Resource temporarily unavailable
at /root/bin/node_modules/levelup/lib/levelup.js:119:34
at /root/bin/node_modules/abstract-leveldown/abstract-leveldown.js:39:16`

Error when stopping and restarting Daemon w/ google-drive-ocamlfuse. It seems like LOCK was not removed when using storjshare killall.

**Comment by 161chihuahuas** [comment]
You can reopen this in storjshare-daemon if it persists
