### ISSUE TITLE
Error: too many open files

### ISSUE THREAD

**Issue by michaldlouhy** [storj-archived/kfs#54]
![image](https://cloud.githubusercontent.com/assets/25122172/23970189/4eb93192-09c9-11e7-84a2-5b673d701870.png)

StorJ Share GUI report an error about too many open files if I tried to start second disk (resource monitor looks there are a very big numbers of I/O operations by StorjShare program). Win 10 v. 1607 64 bit (with all hotfixes and updates), CPU Intel Core i5 M430@2,27 GHz, 8 GB RAM, 256 GB SSD Kingston HyperX Savage, Storj Share 4.1.0, Core Library 6.3.0, Protocol 1.1.0, Electron 1.4.15, Chrome 53.0.2785.143.

![image](https://cloud.githubusercontent.com/assets/25122172/23970491/3e93f0c6-09ca-11e7-9bcd-45a1a5e5e1ff.png)

**Comment by 161chihuahuas** [comment]
https://github.com/Storj/core/issues/666
