### ISSUE TITLE
LevelDB alternative

### ISSUE THREAD

**Issue by yIag2Ew** [storj-archived/kfs#57]
Hi,

Curious why leveldb was used instead of [rocksdb](https://github.com/facebook/rocksdb) or [wiredtiger](https://github.com/wiredtiger/wiredtiger)?

**Comment by 161chihuahuas** [comment]
RocksDB is specifically optimized for flash storage - something that is too specific for the target use case in the storj network. There are no bindings for Node (to my knowledge - or there weren't when developing this package) for WiredTiger, and I may be wrong about this but also feel that it is too heavy for running on the type of low end hardware targeted in the storj network (like CHIPs and Raspberry Pis).
